In [ ]:
#Start in Terminal by running this code:
conda create -n crispresso2 -c bioconda -c conda-forge crispresso2

conda activate crispresso2

CRISPResso --help
CRISPRessoBatch --help

python -m ipykernel install --user --name crispresso2 --display-name "CRISPResso2 env"

conda activate crispresso2

conda install -c conda-forge ipykernel
##conda activate crispresso2

# Install Jupyter Notebook (and/or Lab)
conda install -c conda-forge notebook jupyterlab
# or with mamba if you use it:
# mamba install -c conda-forge notebook jupyterlab

jupyter notebook

In [3]:
#Generate required folders within 'crispresso_project'

from pathlib import Path

for d in ["fastq", "refs", "results"]:
    Path(d).mkdir(exist_ok=True)

print("Subfolders:", [p.name for p in Path(".").iterdir() if p.is_dir()])


import os
print(os.getcwd())

Subfolders: ['results', 'refs', 'fastq']
/Users/pdevant/crispresso_project

In [1]:

#Make project folder and check that CRISPResso is available in this kernel

import os, subprocess, textwrap

# e.g. "/Users/pdevant/projects/crispresso"
project_dir = "/Users/pdevant/crispresso_project"

os.makedirs(project_dir, exist_ok=True)
os.chdir(project_dir)

print("Current directory:", os.getcwd())
print("Contents:", os.listdir("."))

# Check that CRISPResso is available in this kernel
result = subprocess.run(["CRISPResso", "--help"], capture_output=True, text=True)
print("CRISPResso help (first 20 lines):")
print("\n".join(result.stdout.splitlines()[:20]))

Current directory: /Users/pdevant/crispresso_project
Contents: []
CRISPResso help (first 20 lines):
usage: CRISPResso [-h] [--version] [-r1 FASTQ_R1] [-r2 FASTQ_R2]
                  [-a AMPLICON_SEQ] [-an AMPLICON_NAME]
                  [-amas AMPLICON_MIN_ALIGNMENT_SCORE]
                  [--default_min_aln_score DEFAULT_MIN_ALN_SCORE]
                  [--expand_ambiguous_alignments]
                  [--assign_ambiguous_alignments_to_first_reference]
                  [-g GUIDE_SEQ] [-gn GUIDE_NAME] [-fg FLEXIGUIDE_SEQ]
                  [-fh FLEXIGUIDE_HOMOLOGY] [-fgn FLEXIGUIDE_NAME]
                  [--flexiguide_gap_open_penalty FLEXIGUIDE_GAP_OPEN_PENALTY]
                  [--flexiguide_gap_extend_penalty FLEXIGUIDE_GAP_EXTEND_PENALTY]
                  [--discard_guide_positions_overhanging_amplicon_edge]
                  [-e EXPECTED_HDR_AMPLICON_SEQ] [-c CODING_SEQ]
                  [--config_file CONFIG_FILE] [-q MIN_AVERAGE_READ_QUALITY]
                  [-s MIN_SINGLE_BP_QUALITY]
                  [--min_bp_quality_or_N MIN_BP_QUALITY_OR_N]
                  [--file_prefix FILE_PREFIX] [-n NAME]
                  [--display_name DISPLAY_NAME]
                  [--suppress_amplicon_name_truncation] [-o OUTPUT_FOLDER]
                  [-v VERBOSITY] [--split_interleaved_input]
                  [--trim_sequences]

In [6]:
#generate Amplicon file


amplicons_txt = """\
amplicon_name\tamplicon_sequence\tsgRNA_sequence
TNFAIP3_g1\tAATGTGAAACGCCCAACTGCCCCTTCTTCATGTCTGTGAACACCCAGCCTTTATGCCATGAGTGCTCAGAGAGGCGGCAAAAGAATCAAAACAAACTCCCAAAGCTGAACTCCAAGCCGGGCCCTGAGGGGCTCCCTGGCATGGCGCTCGGGGCCTCTCGGGGAGAAGCCTATGAGCCCT\tTATGCCATGAGTGCTCAGAG
TNFAIP3_g2\tAATGCTAAGAAGTTTGGAATCAGGTTCCAATTTCGCCCCTTTGAAAGTGGGTGGAATTTACTTGCCTCTCCACTGGCCTGCCCAGGAATGCTACAGATACCCCATTGTTCTCGGCTATGACAGCCATCATTTTGTACCCTTGGTGACCCTGAAGGACAGTGGGCCTGGTGAGAAAACTGCATTAATTCAC\tCTGTCCTTCAGGGTCACCAA
ZFP36_g1\tTGGCAAGCTCTAGTTCCCTGCAGCTGGGGTGGGGCGTCGCCCTGCATTTTCAGGTGCCTTAACCGACCCATTTCCGCAGAGCCTCCTGTCGCTGAGCCCTGACGTGCCCGTGCCATCCGACCATGGAGGGACTGAGTCCAGCCCAGGCTGGGGCTCCTCGGGACCCTGGAGCCTGAGCCCCTCCGACTCCAGCCCGTCTGGGGTCACCTCCCGCCTGCCTGGCCGCTCCACCAGCCTAGTG\tCCCGTGCCATCCGACCATGG
ZFP36_g2\tGAGCTATGTCGGACCTTCTCAGAGAGTGGGCGCTGCCGCTACGGGGCCAAGTGCCAGTTTGCCCATGGCCTGGGCGAGCTGCGCCAGGCCAATCGCCACCCCAAATACAAGACGGAACTCTGTCACAAGTTCTACCTCCAGGGCCGCTGCCCCTACGGCTCTCGCTGCCACTTCATCCACAACCCTAGCGAAGACCTGGCGGCCCCGGGCCACCCTCCTGTGCTTCGCCAGAGCATCAGCTTCT\tAGAGTTCCGTCTTGTATTTG
DUSP1_g1\tTCCCAGGAGGATACGAAGCGTTTTCGGCTTCCTGCCCGGAGCTGTGCAGCAAACAGTCGACCCCCATGGGGCTCAGCCTTCCCCTGAGTACTAGCGTCCCTGACAGCGCGGAATCTGGGTGCAGTTCCTGCAGTACCCCACTCTACGATCAGGTTAGTAGGTGTCCCTGCCACAGGGAAGAAGTAAGAACTGGCAAAGGCATGGAAGAGTAGTGCCA\tACTAACCTGATCGTAGAGTG
DUSP1_g2\tGTATGAAGGTGCCGTGTCCCGGTGTCACTAATGGGGaaaaaaaaTGTCTTTGTATTCCCAGGAGGATACGAAGCGTTTTCGGCTTCCTGCCCGGAGCTGTGCAGCAAACAGTCGACCCCCATGGGGCTCAGCCTTCCCCTGAGTACTAGCGTCCCTGACAGCGCGGAATCTGGGTGCAGTTCCTGCAGTACCCCACTCTACGATCAGGTTAGT\tGCAAACAGTCGACCCCCATG
MITF_g1\tCCAAGTCCTGAGCTTGCCATGTCCAAACCAGCCTGGCGATCATGTCATGCCACCGGTGCCGGGGAGCAGCGCACCCAACAGCCCCATGGCTATGCTTACGCTTAACTCCAACTGTGAAAAAGAGGTAATTCATGTCTCCTCTCCTCTCCTGTTTTCTTATGCTAAATAACTTGTCTGTTGAATATGATTCCCACACTTAACTGTGGACTCTAGTTTGTCCTTGTGGCCA\tTAAGCGTAAGCATAGCCATG
MITF_g2\tGGCCTGGTCAGTTTCATGTTTGTGCCTGAAGGAAGAGCCGTCTGAAACTCACAAATAACAGCGCTGTTTTCTTTTCCCTCCATGGCTATGTTCAGGTGCAGACCCACCTCGAAAACCCCACCAAGTACCACATACAGCAAGCCCAACGGCAGCAGGTAAAGCAGTACCTTTCTACCACTTTAGCAAATAAACATGCCAACCAAGTCCTGA\tACCACATACAGCAAGCCCAA
FOS_g1\tCAGACTACGAGGCGTCATCCTCCCGCTGCAGCAGCGCGTCCCCGGCCGGGGATAGCCTCTCTTACTACCACTCACCCGCAGACTCCTTCTCCAGCATGGGCTCGCCTGTCAACGCGCAGGTAAGGCTGGCTTCCCGTCGCCGCGGGGCCGGGGGCTTGGGGTCGCGGAGGAGGAGACACCGGGCGGGACGCTCCAGTAGATGAGTAGGGGGCTCCC\tGTAGTAAGAGAGGCTATCCC
FOS_g2\tAGACACTTTTACTGAATGTCGGTCTTTTTTTGTGATTATTCTAGTTATCTCCAGAAGAAGAAGAGAAAAGGAGAATCCGAAGGGAAAGGAATAAGATGGCTGCAGCCAAATGCCGCAACCGGAGGAGGGAGCTGACTGATACACTCCAAGCGGTAGGTACTCTGTGGGTTGCTCCTTTTTAAAACTTAAGGGGAAAGTTGGAGATTGAGCATAAGGGCC\tGCTGACTGATACACTCCAAG
TNF_g1\tGGATCATCTTCTCGAACCCCGAGTGACAAGCCTGTAGCCCATGTTGTAGGTAAGAGCTCTGAGGATGTGTCTTGGAACTTGGAGGGCTAGGATTTGGGGATTGAAGCCCGGCTGATGGTAGGCAGAACTTGGAGACAATGTGAGAAGGACTCGCTGAGCTCAAGGGAAGGGTGGAGGAACAGCACAGGCCTTAGTGGGATA\tAGAGCTCTTACCTACAACAT
TNF_g2\tGCAGCTCCAGTGGCTGAACCGCCGGGCCAATGCCCTCCTGGCCAATGGCGTGGAGCTGAGAGATAACCAGCTGGTGGTGCCATCAGAGGGCCTGTACCTCATCTACTCCCAGGTCCTCTTCAAGGGCCAAGGCTGCCCCTCCACCCATGTGCTCCTCACCCACACCATCAGCCGCATCGCCGTCTCCTACCAGACCAAGGTCAACCTC\tGGAGCTGAGAGATAACCAGC
TLR4_g1\tCTCTAGAGGGCCTGTGCAATTTGACCATTGAAGAATTCCGATTAGCATACTTAGACTACTACCTCGATGATATTATTGACTTATTTAATTGTTTGACAAATGTTTCTTCATTTTCCCTGGTGAGTGTGACTATTGAAAGGGTAAAAGACTTTTCTTATAATTTCGGATGGCAACATTTAGAATTAGTTAACTGTAAATTTGGACAGTTTCCCACATTGAAACTCAAATCTCTC\tATAAGTCAATAATATCATCG
TLR4_g2\tTCTAGAGCACTTGGACCTTTCCAGCAACAAGATTCAAAGTATTTATTGCACAGACTTGCGGGTTCTACATCAAATGCCCCTACTCAATCTCTCTTTAGACCTGTCCCTGAACCCTATGAACTTTATCCAACCAGGTGCATTTAAAGAAATTAGGCTTCATAAGCTGACTTTAAGAAATAATTTTGATAGTTTAAATGTAATGAAAACTTGTATTCAAGGTCTGGCTGGTT\tCCTATGAACTTTATCCAACC
TICAM2_g1\tATGAAGCCCTCAGAGTCCAGAATCTGCTACAAGATGACTTTGGTATCAAACCCGGAATAATCTTTGCTGAGATGCCATGTGGCAGACAGCATTTACAGAATTTAGATGATGCTGTAAATGGGTCTGCATGGACAATCTTATTACTGACTGAAAACTTTTTAAGAGATACTTGGTGTAATTTCCAGTTCTATACGTCCCTAATGAACTCCGTTAACAGGCAGC\tTGTAAATGCTGTCTGCCACA
TICAM2_g2\tTAATGGGTATCGGGAAGTCTAAAATAAATTCCTGCCCTCTTTCTCTCTCTTGGGGTAAAAGGCACAGTGTGGATACAAGTCCAGGATATCATGAGTCAGATTCCAAGAAGTCTGAAGATCTATCCTTGTGTAATGTTGCTGAGCACAGCAATACAACAGAGGGGCCAACAGGAAAGCAGGAGGGAGCTCAGAGCGTGGAAGAGATGTTTGAAG\tTTGGGGTAAAAGGCACAGTG
CD14_g1\tGGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCGCTGCCTCTGGAAGCCACAGGACTTGCACTTTCCAGCTTGCGCCTACGCAACGTGTCGTGGGCGACAGGGCGTTCTTGGCTCGCCGAGCTGCAGCAGTGGCTCAAGCCAGGCCTCAAGGTACTGAGCATTGCCCAAGCACACTCGCCTGCCTTTTCCTGCGAACAGGTTCGCGCCTT\tTCGCCCACGACACGTTGCGT
CD14_g2\tGACACGGTCAAGGCTCTCCGCGTGCGGCGGCTCACAGTGGGAGCCGCACAGGTTCCTGCTCAGCTACTGGTAGGCGCCCTGCGTGTGCTAGCGTACTCCCGCCTCAAGGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCGCTGCCTCTGGAAGCCACAGGACTTGCACTTTCCAGCTTGCGCCTACG\tGGAGTACGCTAGCACACGCA
MAP3K8_g1\tGCCAGCTTGACTGAAGTTCTCACCGTCTCACATTTTTATTTTGTTGTAGGTCATCACTCCCCAAAATGGACGTTACCAAATAGATTCCGATGTTCTCCTGATCCCCTGGAAGCTGACTTACAGGAATATTGGTTCTGATTTTATTCCTCGGGGCGCCTTTGGAAAGGTATACTTGGCACAAGATATAAAGACGAAGAAAAGAATGGCGTGTAAACTGGTATGTGT\tCCAGGGGATCAGGAGAACAT
MAP3K8_g2\tGAGTACATGAGCACTGGAAGTGACAATAAAGAAGAGATTGATTTATTAATTAAACATTTAAATGTGTCTGATGTAATAGACATTATGGAAAATCTTTATGCAAGTGAAGAGCCAGCAGTTTATGAACCCAGTCTAATGACCATGTGTCAAGACAGTAATCAAAACGATGAGCGTTCTAAGTCTCTGCTGCTTAGTGGCCAAGAGGTACCATGGTTGTCATCAGTCAGATATGGAACTGTGGAGGATTTGCTTGC\tTGACACATGGTCATTAGACT
B2M_ABE\tTGTCTTTCAGCAAGGACTGGTCTTTCTATCTCTTGTACTACACTGAATTCACCCCCACTGAAAAAGATGAGTATGCCTGCCGTGTGAACCATGTGACTTTGTCACAGCCCAAGATAGTTAAGTGGGGTAAGTCTTACATTCTTTTGTAAGCTGCTGAAAGTTGTGTATGAGTAGTCATATCATAAAGCTGCTTTGATATAAAAAAGGTCTATGGCCATACTACCCTGAATGAGTCCC\tcttaccccacttaactatct
"""


with open("refs/amplicons.txt", "w") as f:
    f.write(amplicons_txt)

print(open("refs/amplicons.txt").read())

amplicon_name	amplicon_sequence	sgRNA_sequence
TNFAIP3_g1	AATGTGAAACGCCCAACTGCCCCTTCTTCATGTCTGTGAACACCCAGCCTTTATGCCATGAGTGCTCAGAGAGGCGGCAAAAGAATCAAAACAAACTCCCAAAGCTGAACTCCAAGCCGGGCCCTGAGGGGCTCCCTGGCATGGCGCTCGGGGCCTCTCGGGGAGAAGCCTATGAGCCCT	TATGCCATGAGTGCTCAGAG
TNFAIP3_g2	AATGCTAAGAAGTTTGGAATCAGGTTCCAATTTCGCCCCTTTGAAAGTGGGTGGAATTTACTTGCCTCTCCACTGGCCTGCCCAGGAATGCTACAGATACCCCATTGTTCTCGGCTATGACAGCCATCATTTTGTACCCTTGGTGACCCTGAAGGACAGTGGGCCTGGTGAGAAAACTGCATTAATTCAC	CTGTCCTTCAGGGTCACCAA
ZFP36_g1	TGGCAAGCTCTAGTTCCCTGCAGCTGGGGTGGGGCGTCGCCCTGCATTTTCAGGTGCCTTAACCGACCCATTTCCGCAGAGCCTCCTGTCGCTGAGCCCTGACGTGCCCGTGCCATCCGACCATGGAGGGACTGAGTCCAGCCCAGGCTGGGGCTCCTCGGGACCCTGGAGCCTGAGCCCCTCCGACTCCAGCCCGTCTGGGGTCACCTCCCGCCTGCCTGGCCGCTCCACCAGCCTAGTG	CCCGTGCCATCCGACCATGG
ZFP36_g2	GAGCTATGTCGGACCTTCTCAGAGAGTGGGCGCTGCCGCTACGGGGCCAAGTGCCAGTTTGCCCATGGCCTGGGCGAGCTGCGCCAGGCCAATCGCCACCCCAAATACAAGACGGAACTCTGTCACAAGTTCTACCTCCAGGGCCGCTGCCCCTACGGCTCTCGCTGCCACTTCATCCACAACCCTAGCGAAGACCTGGCGGCCCCGGGCCACCCTCCTGTGCTTCGCCAGAGCATCAGCTTCT	AGAGTTCCGTCTTGTATTTG
DUSP1_g1	TCCCAGGAGGATACGAAGCGTTTTCGGCTTCCTGCCCGGAGCTGTGCAGCAAACAGTCGACCCCCATGGGGCTCAGCCTTCCCCTGAGTACTAGCGTCCCTGACAGCGCGGAATCTGGGTGCAGTTCCTGCAGTACCCCACTCTACGATCAGGTTAGTAGGTGTCCCTGCCACAGGGAAGAAGTAAGAACTGGCAAAGGCATGGAAGAGTAGTGCCA	ACTAACCTGATCGTAGAGTG
DUSP1_g2	GTATGAAGGTGCCGTGTCCCGGTGTCACTAATGGGGaaaaaaaaTGTCTTTGTATTCCCAGGAGGATACGAAGCGTTTTCGGCTTCCTGCCCGGAGCTGTGCAGCAAACAGTCGACCCCCATGGGGCTCAGCCTTCCCCTGAGTACTAGCGTCCCTGACAGCGCGGAATCTGGGTGCAGTTCCTGCAGTACCCCACTCTACGATCAGGTTAGT	GCAAACAGTCGACCCCCATG
MITF_g1	CCAAGTCCTGAGCTTGCCATGTCCAAACCAGCCTGGCGATCATGTCATGCCACCGGTGCCGGGGAGCAGCGCACCCAACAGCCCCATGGCTATGCTTACGCTTAACTCCAACTGTGAAAAAGAGGTAATTCATGTCTCCTCTCCTCTCCTGTTTTCTTATGCTAAATAACTTGTCTGTTGAATATGATTCCCACACTTAACTGTGGACTCTAGTTTGTCCTTGTGGCCA	TAAGCGTAAGCATAGCCATG
MITF_g2	GGCCTGGTCAGTTTCATGTTTGTGCCTGAAGGAAGAGCCGTCTGAAACTCACAAATAACAGCGCTGTTTTCTTTTCCCTCCATGGCTATGTTCAGGTGCAGACCCACCTCGAAAACCCCACCAAGTACCACATACAGCAAGCCCAACGGCAGCAGGTAAAGCAGTACCTTTCTACCACTTTAGCAAATAAACATGCCAACCAAGTCCTGA	ACCACATACAGCAAGCCCAA
FOS_g1	CAGACTACGAGGCGTCATCCTCCCGCTGCAGCAGCGCGTCCCCGGCCGGGGATAGCCTCTCTTACTACCACTCACCCGCAGACTCCTTCTCCAGCATGGGCTCGCCTGTCAACGCGCAGGTAAGGCTGGCTTCCCGTCGCCGCGGGGCCGGGGGCTTGGGGTCGCGGAGGAGGAGACACCGGGCGGGACGCTCCAGTAGATGAGTAGGGGGCTCCC	GTAGTAAGAGAGGCTATCCC
FOS_g2	AGACACTTTTACTGAATGTCGGTCTTTTTTTGTGATTATTCTAGTTATCTCCAGAAGAAGAAGAGAAAAGGAGAATCCGAAGGGAAAGGAATAAGATGGCTGCAGCCAAATGCCGCAACCGGAGGAGGGAGCTGACTGATACACTCCAAGCGGTAGGTACTCTGTGGGTTGCTCCTTTTTAAAACTTAAGGGGAAAGTTGGAGATTGAGCATAAGGGCC	GCTGACTGATACACTCCAAG
TNF_g1	GGATCATCTTCTCGAACCCCGAGTGACAAGCCTGTAGCCCATGTTGTAGGTAAGAGCTCTGAGGATGTGTCTTGGAACTTGGAGGGCTAGGATTTGGGGATTGAAGCCCGGCTGATGGTAGGCAGAACTTGGAGACAATGTGAGAAGGACTCGCTGAGCTCAAGGGAAGGGTGGAGGAACAGCACAGGCCTTAGTGGGATA	AGAGCTCTTACCTACAACAT
TNF_g2	GCAGCTCCAGTGGCTGAACCGCCGGGCCAATGCCCTCCTGGCCAATGGCGTGGAGCTGAGAGATAACCAGCTGGTGGTGCCATCAGAGGGCCTGTACCTCATCTACTCCCAGGTCCTCTTCAAGGGCCAAGGCTGCCCCTCCACCCATGTGCTCCTCACCCACACCATCAGCCGCATCGCCGTCTCCTACCAGACCAAGGTCAACCTC	GGAGCTGAGAGATAACCAGC
TLR4_g1	CTCTAGAGGGCCTGTGCAATTTGACCATTGAAGAATTCCGATTAGCATACTTAGACTACTACCTCGATGATATTATTGACTTATTTAATTGTTTGACAAATGTTTCTTCATTTTCCCTGGTGAGTGTGACTATTGAAAGGGTAAAAGACTTTTCTTATAATTTCGGATGGCAACATTTAGAATTAGTTAACTGTAAATTTGGACAGTTTCCCACATTGAAACTCAAATCTCTC	ATAAGTCAATAATATCATCG
TLR4_g2	TCTAGAGCACTTGGACCTTTCCAGCAACAAGATTCAAAGTATTTATTGCACAGACTTGCGGGTTCTACATCAAATGCCCCTACTCAATCTCTCTTTAGACCTGTCCCTGAACCCTATGAACTTTATCCAACCAGGTGCATTTAAAGAAATTAGGCTTCATAAGCTGACTTTAAGAAATAATTTTGATAGTTTAAATGTAATGAAAACTTGTATTCAAGGTCTGGCTGGTT	CCTATGAACTTTATCCAACC
TICAM2_g1	ATGAAGCCCTCAGAGTCCAGAATCTGCTACAAGATGACTTTGGTATCAAACCCGGAATAATCTTTGCTGAGATGCCATGTGGCAGACAGCATTTACAGAATTTAGATGATGCTGTAAATGGGTCTGCATGGACAATCTTATTACTGACTGAAAACTTTTTAAGAGATACTTGGTGTAATTTCCAGTTCTATACGTCCCTAATGAACTCCGTTAACAGGCAGC	TGTAAATGCTGTCTGCCACA
TICAM2_g2	TAATGGGTATCGGGAAGTCTAAAATAAATTCCTGCCCTCTTTCTCTCTCTTGGGGTAAAAGGCACAGTGTGGATACAAGTCCAGGATATCATGAGTCAGATTCCAAGAAGTCTGAAGATCTATCCTTGTGTAATGTTGCTGAGCACAGCAATACAACAGAGGGGCCAACAGGAAAGCAGGAGGGAGCTCAGAGCGTGGAAGAGATGTTTGAAG	TTGGGGTAAAAGGCACAGTG
CD14_g1	GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCGCTGCCTCTGGAAGCCACAGGACTTGCACTTTCCAGCTTGCGCCTACGCAACGTGTCGTGGGCGACAGGGCGTTCTTGGCTCGCCGAGCTGCAGCAGTGGCTCAAGCCAGGCCTCAAGGTACTGAGCATTGCCCAAGCACACTCGCCTGCCTTTTCCTGCGAACAGGTTCGCGCCTT	TCGCCCACGACACGTTGCGT
CD14_g2	GACACGGTCAAGGCTCTCCGCGTGCGGCGGCTCACAGTGGGAGCCGCACAGGTTCCTGCTCAGCTACTGGTAGGCGCCCTGCGTGTGCTAGCGTACTCCCGCCTCAAGGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCGCTGCCTCTGGAAGCCACAGGACTTGCACTTTCCAGCTTGCGCCTACG	GGAGTACGCTAGCACACGCA
MAP3K8_g1	GCCAGCTTGACTGAAGTTCTCACCGTCTCACATTTTTATTTTGTTGTAGGTCATCACTCCCCAAAATGGACGTTACCAAATAGATTCCGATGTTCTCCTGATCCCCTGGAAGCTGACTTACAGGAATATTGGTTCTGATTTTATTCCTCGGGGCGCCTTTGGAAAGGTATACTTGGCACAAGATATAAAGACGAAGAAAAGAATGGCGTGTAAACTGGTATGTGT	CCAGGGGATCAGGAGAACAT
MAP3K8_g2	GAGTACATGAGCACTGGAAGTGACAATAAAGAAGAGATTGATTTATTAATTAAACATTTAAATGTGTCTGATGTAATAGACATTATGGAAAATCTTTATGCAAGTGAAGAGCCAGCAGTTTATGAACCCAGTCTAATGACCATGTGTCAAGACAGTAATCAAAACGATGAGCGTTCTAAGTCTCTGCTGCTTAGTGGCCAAGAGGTACCATGGTTGTCATCAGTCAGATATGGAACTGTGGAGGATTTGCTTGC	TGACACATGGTCATTAGACT
B2M_ABE	TGTCTTTCAGCAAGGACTGGTCTTTCTATCTCTTGTACTACACTGAATTCACCCCCACTGAAAAAGATGAGTATGCCTGCCGTGTGAACCATGTGACTTTGTCACAGCCCAAGATAGTTAAGTGGGGTAAGTCTTACATTCTTTTGTAAGCTGCTGAAAGTTGTGTATGAGTAGTCATATCATAAAGCTGCTTTGATATAAAAAAGGTCTATGGCCATACTACCCTGAATGAGTCCC	cttaccccacttaactatct

In [23]:
##Generate batch files

import pandas as pd
from pathlib import Path
import re

fastq_dir = Path("fastq")

# 1. Collect all FASTQ filenames
fastqs = sorted([f.name for f in fastq_dir.glob("*.fastq.gz")])
len(fastqs), fastqs[:5]


def extract_sample_id(filename):
    """
    Extract sample ID from filenames like:
      CD14_g1_D1_S141_L001_R1_001.fastq.gz
    → CD14_g1_D1
    """
    return filename.split("_S")[0]

# Test:
for f in fastqs[:10]:
    print(f, "→", extract_sample_id(f))



data = {}
for f in fastqs:
    sample_id = extract_sample_id(f)
    if sample_id not in data:
        data[sample_id] = {"sample_name": sample_id}
    if "_R1_" in f:
        data[sample_id]["fastq_r1"] = f"fastq/{f}"
    if "_R2_" in f:
        data[sample_id]["fastq_r2"] = f"fastq/{f}"

df = pd.DataFrame(data.values())
df = df.sort_values("sample_name")
df.head()


def is_abe(sample_name):
    return ("ABE" in sample_name) or ("CBE" in sample_name)

df["is_ABE"] = df["sample_name"].apply(is_abe)

df["abe_amplicon"] = df["is_ABE"].apply(lambda x: "B2M_ABE" if x else None)



# True for ABE/CBE/BE samples, False for pure KO / other controls
df["is_ABE"] = df["sample_name"].str.contains("ABE|CBE|BE_")
df[["sample_name", "is_ABE"]].head(20)


import numpy as np

# Start with all NaN
df["amplicon_name"] = np.nan

# KO samples: derive GENE_g1 / GENE_g2 from sample_name
mask_ko = ~df["is_ABE"]
df.loc[mask_ko, "amplicon_name"] = (
    df.loc[mask_ko, "sample_name"]
      .str.extract(r"^([^_]+_g[12])")[0]   # captures e.g. "TNFAIP3_g1"
)

# ABE samples: all share the same amplicon name
mask_abe = df["is_ABE"]
df.loc[mask_abe, "amplicon_name"] = "B2M_ABE"

df.head(20)


ko_df = df[~df["is_ABE"]].copy()

ko_df = ko_df[["sample_name", "fastq_r1", "fastq_r2", "amplicon_name"]]

ko_out = Path("refs/KO_batch.txt")
ko_df.to_csv(ko_out, sep="\t", index=False)
print(f"Wrote {ko_out}")
ko_df.head()



abe_df = df[df["is_ABE"]].copy()

abe_df = abe_df[["sample_name", "fastq_r1", "fastq_r2", "amplicon_name"]]

abe_out = Path("refs/ABE_batch.txt")
abe_df.to_csv(abe_out, sep="\t", index=False)
print(f"Wrote {abe_out}")
abe_df.head()

CD14_g1_D1_S141_L001_R1_001.fastq.gz → CD14_g1_D1
CD14_g1_D1_S141_L001_R2_001.fastq.gz → CD14_g1_D1
CD14_g1_D2_S142_L001_R1_001.fastq.gz → CD14_g1_D2
CD14_g1_D2_S142_L001_R2_001.fastq.gz → CD14_g1_D2
CD14_g1_D3_S143_L001_R1_001.fastq.gz → CD14_g1_D3
CD14_g1_D3_S143_L001_R2_001.fastq.gz → CD14_g1_D3
CD14_g1_D4_S144_L001_R1_001.fastq.gz → CD14_g1_D4
CD14_g1_D4_S144_L001_R2_001.fastq.gz → CD14_g1_D4
CD14_g1_D5_S145_L001_R1_001.fastq.gz → CD14_g1_D5
CD14_g1_D5_S145_L001_R2_001.fastq.gz → CD14_g1_D5
Wrote refs/KO_batch.txt
Wrote refs/ABE_batch.txt

/var/folders/9l/dyp50m2d6s30t17769kjdmt00000gr/T/ipykernel_68403/4023315626.py:64: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['CD14_g1' 'CD14_g1' 'CD14_g1' 'CD14_g1' 'CD14_g1' 'CD14_g1' 'CD14_g2'
 'CD14_g2' 'CD14_g2' 'CD14_g2' 'CD14_g2' 'CD14_g2' nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan 'DUSP1_g1' 'DUSP1_g1'
 'DUSP1_g1' 'DUSP1_g1' 'DUSP1_g1' 'DUSP1_g1' 'DUSP1_g2' 'DUSP1_g2'
 'DUSP1_g2' 'DUSP1_g2' 'DUSP1_g2' 'DUSP1_g2' 'FOS_g1' 'FOS_g1' 'FOS_g1'
 'FOS_g1' 'FOS_g1' 'FOS_g1' 'FOS_g2' 'FOS_g2' 'FOS_g2' 'FOS_g2' 'FOS_g2'
 'FOS_g2' 'MAP3K8_g1' 'MAP3K8_g1' 'MAP3K8_g1' 'MAP3K8_g1' 'MAP3K8_g1'
 'MAP3K8_g1' 'MAP3K8_g2' 'MAP3K8_g2' 'MAP3K8_g2' 'MAP3K8_g2' 'MAP3K8_g2'
 'MAP3K8_g2' 'MITF_g1' 'MITF_g1' 'MITF_g1' 'MITF_g1' 'MITF_g1' 'MITF_g1'
 'MITF_g2' 'MITF_g2' 'MITF_g2' 'MITF_g2' 'MITF_g2' 'MITF_g2' nan
 'TICAM2_g1' 'TICAM2_g1' 'TICAM2_g1' 'TICAM2_g1' 'TICAM2_g1' 'TICAM2_g1'
 'TICAM2_g2' 'TICAM2_g2' 'TICAM2_g2' 'TICAM2_g2' 'TICAM2_g2' 'TICAM2_g2'
 'TLR4_g1' 'TLR4_g1' 'TLR4_g1' 'TLR4_g1' 'TLR4_g1' 'TLR4_g1' 'TLR4_g2'
 'TLR4_g2' 'TLR4_g2' 'TLR4_g2' 'TLR4_g2' 'TLR4_g2' 'TNFAIP3_g1'
 'TNFAIP3_g1' 'TNFAIP3_g1' 'TNFAIP3_g1' 'TNFAIP3_g1' 'TNFAIP3_g1'
 'TNFAIP3_g2' 'TNFAIP3_g2' 'TNFAIP3_g2' 'TNFAIP3_g2' 'TNFAIP3_g2'
 'TNFAIP3_g2' 'TNF_g1' 'TNF_g1' 'TNF_g1' 'TNF_g1' 'TNF_g1' 'TNF_g1'
 'TNF_g2' 'TNF_g2' 'TNF_g2' 'TNF_g2' 'TNF_g2' 'TNF_g2' nan 'ZFP36_g1'
 'ZFP36_g1' 'ZFP36_g1' 'ZFP36_g1' 'ZFP36_g1' 'ZFP36_g1' 'ZFP36_g2'
 'ZFP36_g2' 'ZFP36_g2' 'ZFP36_g2' 'ZFP36_g2' 'ZFP36_g2']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask_ko, "amplicon_name"] = (

,sample_name,fastq_r1,fastq_r2,amplicon_name
19,D1_A14_NGG-ABE_0-2_ul,fastq/D1_A14_NGG-ABE_0-2_ul_S5_L001_R1_001.fas...,fastq/D1_A14_NGG-ABE_0-2_ul_S5_L001_R2_001.fas...,B2M_ABE
20,D1_A14_NGG-ABE_20_ul,fastq/D1_A14_NGG-ABE_20_ul_S7_L001_R1_001.fast...,fastq/D1_A14_NGG-ABE_20_ul_S7_L001_R2_001.fast...,B2M_ABE
21,D1_A14_NGG-ABE_2_ul,fastq/D1_A14_NGG-ABE_2_ul_S6_L001_R1_001.fastq.gz,fastq/D1_A14_NGG-ABE_2_ul_S6_L001_R2_001.fastq.gz,B2M_ABE
22,D1_B56_CBE_0-2_ul,fastq/D1_B56_CBE_0-2_ul_S2_L001_R1_001.fastq.gz,fastq/D1_B56_CBE_0-2_ul_S2_L001_R2_001.fastq.gz,B2M_ABE
23,D1_B56_CBE_20_ul,fastq/D1_B56_CBE_20_ul_S4_L001_R1_001.fastq.gz,fastq/D1_B56_CBE_20_ul_S4_L001_R2_001.fastq.gz,B2M_ABE

In [26]:
## Generate new batch file (merge of previous batch file and amplicon file)

import pandas as pd
from pathlib import Path

# Load your existing KO batch (sample_name, fastq_r1, fastq_r2, amplicon_name)
ko_batch = pd.read_csv("refs/KO_batch.txt", sep="\t")

# Load amplicon definitions (amplicon_name, amplicon_sequence, sgRNA_sequence)
amp = pd.read_csv("refs/amplicons.txt", sep="\t")

ko_batch.head(), amp.head()

merged = ko_batch.merge(amp, on="amplicon_name", how="left")

# Sanity check for missing mappings
missing = merged[merged["amplicon_sequence"].isna()]
print("Rows with missing amplicon_sequence:", len(missing))
if len(missing) > 0:
    display(missing[["sample_name", "amplicon_name"]])


ko_batch2 = merged.rename(columns={
    "sample_name": "name",
    "amplicon_sequence": "amplicon_seq",
    "sgRNA_sequence": "guide_seq",
})

ko_batch2 = ko_batch2[["name", "fastq_r1", "fastq_r2", "amplicon_seq", "guide_seq"]]

out_ko = Path("refs/KO_batch_CRISPResso2.txt")
ko_batch2.to_csv(out_ko, sep="\t", index=False)
print(f"Wrote {out_ko}")
ko_batch2.head()

Rows with missing amplicon_sequence: 20

        sample_name amplicon_name
12       D1_A14_A90           NaN
13      D1_A14_B100           NaN
14       D1_A14_B96           NaN
15       D1_A14_B97           NaN
16       D1_A14_B98           NaN
17       D1_A14_B99           NaN
18       D1_A14_C01           NaN
19      D1_unreated           NaN
20       D2_A14_A90           NaN
21      D2_A14_B100           NaN
22       D2_A14_B96           NaN
23       D2_A14_B97           NaN
24       D2_A14_B98           NaN
25       D2_A14_B99           NaN
26       D2_A14_C01           NaN
27      D2_unreated           NaN
28      D3_unreated           NaN
29      D4_unreated           NaN
78   TF_lib_plasmid           NaN
127    Undetermined           NaN

Wrote refs/KO_batch_CRISPResso2.txt

,name,fastq_r1,fastq_r2,amplicon_seq,guide_seq
0,CD14_g1_D1,fastq/CD14_g1_D1_S141_L001_R1_001.fastq.gz,fastq/CD14_g1_D1_S141_L001_R2_001.fastq.gz,GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCG...,TCGCCCACGACACGTTGCGT
1,CD14_g1_D2,fastq/CD14_g1_D2_S142_L001_R1_001.fastq.gz,fastq/CD14_g1_D2_S142_L001_R2_001.fastq.gz,GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCG...,TCGCCCACGACACGTTGCGT
2,CD14_g1_D3,fastq/CD14_g1_D3_S143_L001_R1_001.fastq.gz,fastq/CD14_g1_D3_S143_L001_R2_001.fastq.gz,GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCG...,TCGCCCACGACACGTTGCGT
3,CD14_g1_D4,fastq/CD14_g1_D4_S144_L001_R1_001.fastq.gz,fastq/CD14_g1_D4_S144_L001_R2_001.fastq.gz,GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCG...,TCGCCCACGACACGTTGCGT
4,CD14_g1_D5,fastq/CD14_g1_D5_S145_L001_R1_001.fastq.gz,fastq/CD14_g1_D5_S145_L001_R2_001.fastq.gz,GGAACTGACGCTCGAGGACCTAAAGATAACCGGCACCATGCCTCCG...,TCGCCCACGACACGTTGCGT

In [33]:
## Running CRISPResso with updated batch file for KO samples


!CRISPRessoBatch \
    --batch_settings refs/KO_batch_CRISPResso2.txt \
    --min_average_read_quality 25 \
    --min_single_bp_quality 20 \
    --plot_window_size 20 \
    --default_min_aln_score 40 \
    --name KO_run \
    --output_folder results/KO_batch

INFO  @ Thu, 11 Dec 2025 20:39:36 (0.0% done):

                             ~~~CRISPRessoBatch~~~
       -Analysis of CRISPR/Cas9 outcomes from batch deep sequencing data-

                _                                               _
               '  )                                            '  )
               .-'             _________________               .-'
              (____           | __    ___ __    |             (____
           C)|     \          ||__) /\ | /  |__||          C)|     \
             \     /          ||__)/--\| \__|  ||            \     /
              \___/           |_________________|             \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Thu, 11 Dec 2025 20:39:36 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run

WARNING @ Thu, 11 Dec 2025 20:39:36 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run already exists.

/opt/miniconda3/envs/crispresso2/lib/python3.12/site-packages/CRISPResso2/CRISPRessoBatchCORE.py:220: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  batch_params[arg] = getattr(args, arg)
INFO  @ Thu, 11 Dec 2025 20:39:37 (0.0% done):
	 Running CRISPResso with 1 processes

INFO  @ Thu, 11 Dec 2025 20:39:37 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Thu, 11 Dec 2025 20:39:37 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run/CRISPResso_on_CD14_g1_D1 already exists.

INFO  @ Thu, 11 Dec 2025 20:39:37 (2.0% done):
	 Computing quantification windows

INFO  @ Thu, 11 Dec 2025 20:39:37 (2.0% done):
	 Counting reads in input

INFO  @ Thu, 11 Dec 2025 20:39:37 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Thu, 11 Dec 2025 20:39:38 (6.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:38 (7.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:38 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Aligning sequences...

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Iterating over fastq file to identify reads; 100000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Finished reading fastq file; 3854 unique reads found of 106304 total reads found

INFO  @ Thu, 11 Dec 2025 20:39:40 (7.0% done):
	 Processing Reads; 0 Completed out of 3854 Unique Reads

INFO  @ Thu, 11 Dec 2025 20:39:41 (7.0% done):
	 Finished reads; N_TOT_READS: 106304 N_COMPUTED_ALN: 3020 N_CACHED_ALN: 58356 N_COMPUTED_NOTALN: 834 N_CACHED_NOTALN: 44094

INFO  @ Thu, 11 Dec 2025 20:39:41 (20.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:41 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Thu, 11 Dec 2025 20:39:41 (30.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:41 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Thu, 11 Dec 2025 20:39:41 (40.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:41 (40.0% done):
	 Saving processed data...

INFO  @ Thu, 11 Dec 2025 20:39:41 (40.0% done):
	 Making Plots...

INFO  @ Thu, 11 Dec 2025 20:39:42 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Thu, 11 Dec 2025 20:39:46 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:46 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:46 (48.0% done):
	 Removing Intermediate files...

WARNING @ Thu, 11 Dec 2025 20:39:46 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 106304, Aligned reads: 61376.

WARNING @ Thu, 11 Dec 2025 20:39:46 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 33537, Substitutions outside window: 31575.

INFO  @ Thu, 11 Dec 2025 20:39:46 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Thu, 11 Dec 2025 20:39:46 (100.0% done):
	 Analysis Complete!

INFO  @ Thu, 11 Dec 2025 20:39:46 (10.7% done):
	 Completed 1/122 runs

INFO  @ Thu, 11 Dec 2025 20:39:46 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Thu, 11 Dec 2025 20:39:46 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run/CRISPResso_on_CD14_g1_D2 already exists.

INFO  @ Thu, 11 Dec 2025 20:39:46 (2.0% done):
	 Computing quantification windows

INFO  @ Thu, 11 Dec 2025 20:39:46 (2.0% done):
	 Counting reads in input

INFO  @ Thu, 11 Dec 2025 20:39:46 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Thu, 11 Dec 2025 20:39:47 (6.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:47 (7.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:47 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Thu, 11 Dec 2025 20:39:48 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Thu, 11 Dec 2025 20:39:48 (7.0% done):
	 Aligning sequences...

INFO  @ Thu, 11 Dec 2025 20:39:49 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:39:49 (7.0% done):
	 Finished reading fastq file; 3770 unique reads found of 68648 total reads found

INFO  @ Thu, 11 Dec 2025 20:39:49 (7.0% done):
	 Processing Reads; 0 Completed out of 3770 Unique Reads

INFO  @ Thu, 11 Dec 2025 20:39:49 (7.0% done):
	 Finished reads; N_TOT_READS: 68648 N_COMPUTED_ALN: 3453 N_CACHED_ALN: 54935 N_COMPUTED_NOTALN: 317 N_CACHED_NOTALN: 9943

INFO  @ Thu, 11 Dec 2025 20:39:49 (20.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:49 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Thu, 11 Dec 2025 20:39:50 (30.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:50 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Thu, 11 Dec 2025 20:39:50 (40.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:50 (40.0% done):
	 Saving processed data...

INFO  @ Thu, 11 Dec 2025 20:39:50 (40.0% done):
	 Making Plots...

INFO  @ Thu, 11 Dec 2025 20:39:50 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Thu, 11 Dec 2025 20:39:54 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:54 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:54 (48.0% done):
	 Removing Intermediate files...

WARNING @ Thu, 11 Dec 2025 20:39:54 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 68648, Aligned reads: 58388.

WARNING @ Thu, 11 Dec 2025 20:39:54 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 40282, Substitutions outside window: 38981.

INFO  @ Thu, 11 Dec 2025 20:39:54 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Thu, 11 Dec 2025 20:39:54 (100.0% done):
	 Analysis Complete!

INFO  @ Thu, 11 Dec 2025 20:39:55 (11.3% done):
	 Completed 2/122 runs

INFO  @ Thu, 11 Dec 2025 20:39:55 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Thu, 11 Dec 2025 20:39:55 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run/CRISPResso_on_CD14_g1_D3 already exists.

INFO  @ Thu, 11 Dec 2025 20:39:55 (2.0% done):
	 Computing quantification windows

INFO  @ Thu, 11 Dec 2025 20:39:55 (2.0% done):
	 Counting reads in input

INFO  @ Thu, 11 Dec 2025 20:39:55 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Thu, 11 Dec 2025 20:39:57 (6.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:57 (7.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:39:57 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 2 seconds

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Aligning sequences...

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Iterating over fastq file to identify reads; 100000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Finished reading fastq file; 6359 unique reads found of 119108 total reads found

INFO  @ Thu, 11 Dec 2025 20:39:59 (7.0% done):
	 Processing Reads; 0 Completed out of 6359 Unique Reads

INFO  @ Thu, 11 Dec 2025 20:40:00 (7.0% done):
	 Finished reads; N_TOT_READS: 119108 N_COMPUTED_ALN: 5354 N_CACHED_ALN: 78889 N_COMPUTED_NOTALN: 1005 N_CACHED_NOTALN: 33860

INFO  @ Thu, 11 Dec 2025 20:40:00 (20.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:00 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Thu, 11 Dec 2025 20:40:01 (30.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:01 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Thu, 11 Dec 2025 20:40:01 (40.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:01 (40.0% done):
	 Saving processed data...

INFO  @ Thu, 11 Dec 2025 20:40:01 (40.0% done):
	 Making Plots...

INFO  @ Thu, 11 Dec 2025 20:40:01 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Thu, 11 Dec 2025 20:40:06 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:06 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:06 (48.0% done):
	 Removing Intermediate files...

WARNING @ Thu, 11 Dec 2025 20:40:06 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 119108, Aligned reads: 84243.

WARNING @ Thu, 11 Dec 2025 20:40:06 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 82445, Substitutions outside window: 80549.

INFO  @ Thu, 11 Dec 2025 20:40:06 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Thu, 11 Dec 2025 20:40:06 (100.0% done):
	 Analysis Complete!

INFO  @ Thu, 11 Dec 2025 20:40:06 (12.0% done):
	 Completed 3/122 runs

INFO  @ Thu, 11 Dec 2025 20:40:06 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Thu, 11 Dec 2025 20:40:06 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_KO_run/CRISPResso_on_CD14_g1_D4 already exists.

INFO  @ Thu, 11 Dec 2025 20:40:06 (2.0% done):
	 Computing quantification windows

INFO  @ Thu, 11 Dec 2025 20:40:06 (2.0% done):
	 Counting reads in input

INFO  @ Thu, 11 Dec 2025 20:40:06 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Thu, 11 Dec 2025 20:40:08 (6.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:08 (7.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:08 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 2 seconds

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Aligning sequences...

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Iterating over fastq file to identify reads; 100000 reads identified.

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Finished reading fastq file; 5614 unique reads found of 104879 total reads found

INFO  @ Thu, 11 Dec 2025 20:40:10 (7.0% done):
	 Processing Reads; 0 Completed out of 5614 Unique Reads

INFO  @ Thu, 11 Dec 2025 20:40:11 (7.0% done):
	 Finished reads; N_TOT_READS: 104879 N_COMPUTED_ALN: 5061 N_CACHED_ALN: 80264 N_COMPUTED_NOTALN: 553 N_CACHED_NOTALN: 19001

INFO  @ Thu, 11 Dec 2025 20:40:11 (20.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:11 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Thu, 11 Dec 2025 20:40:11 (30.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:11 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Thu, 11 Dec 2025 20:40:11 (40.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:11 (40.0% done):
	 Saving processed data...

INFO  @ Thu, 11 Dec 2025 20:40:11 (40.0% done):
	 Making Plots...

INFO  @ Thu, 11 Dec 2025 20:40:12 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Thu, 11 Dec 2025 20:40:16 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:16 (48.0% done):
	 Done!

INFO  @ Thu, 11 Dec 2025 20:40:16 (48.0% done):
	 Removing Intermediate files...

WARNING @ Thu, 11 Dec 2025 20:40:16 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 104879, Aligned reads: 85325.

WARNING @ Thu, 11 Dec 2025 20:40:16 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 96543, Substitutions outside window: 94121.

INFO  @ Thu, 11 Dec 2025 20:40:16 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Thu, 11 Dec 2025 20:40:16 (100.0% done):
	 Analysis Complete!

INFO  @ Thu, 11 Dec 2025 20:40:16 (12.6% done):
	 Completed 4/122 runs

INFO  @ Thu, 11 Dec 2025 20:40:17 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]

In [43]:
## Run CRISPResso on BE samples using ABE mode

!CRISPRessoBatch \
    --batch_settings refs/ABE-batch2.txt \
    --base_editor_output \
    --conversion_nuc_from A \
    --conversion_nuc_to G \
    --min_average_read_quality 25 \
    --min_single_bp_quality 20 \
    --default_min_aln_score 50 \
    --name BE_AtoG \
    --output_folder results/BE_AtoG

INFO  @ Fri, 12 Dec 2025 17:43:05 (0.0% done):

                             ~~~CRISPRessoBatch~~~
       -Analysis of CRISPR/Cas9 outcomes from batch deep sequencing data-

                _                                               _
               '  )                                            '  )
               .-'             _________________               .-'
              (____           | __    ___ __    |             (____
           C)|     \          ||__) /\ | /  |__||          C)|     \
             \     /          ||__)/--\| \__|  ||            \     /
              \___/           |_________________|             \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:43:06 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG

WARNING @ Fri, 12 Dec 2025 17:43:06 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG already exists.

/opt/miniconda3/envs/crispresso2/lib/python3.12/site-packages/CRISPResso2/CRISPRessoBatchCORE.py:220: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  batch_params[arg] = getattr(args, arg)
INFO  @ Fri, 12 Dec 2025 17:43:06 (0.0% done):
	 Running CRISPResso with 1 processes

INFO  @ Fri, 12 Dec 2025 17:43:06 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Fri, 12 Dec 2025 17:43:06 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG/CRISPResso_on_D1_A14_NGG-ABE_0-2_ul already exists.

INFO  @ Fri, 12 Dec 2025 17:43:06 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:43:06 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:43:06 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:43:07 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:07 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:07 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:43:08 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:43:08 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:43:08 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:43:08 (7.0% done):
	 Finished reading fastq file; 2710 unique reads found of 63230 total reads found

INFO  @ Fri, 12 Dec 2025 17:43:08 (7.0% done):
	 Processing Reads; 0 Completed out of 2710 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:43:09 (7.0% done):
	 Finished reads; N_TOT_READS: 63230 N_COMPUTED_ALN: 1618 N_CACHED_ALN: 35746 N_COMPUTED_NOTALN: 1092 N_CACHED_NOTALN: 24774

INFO  @ Fri, 12 Dec 2025 17:43:09 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:09 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:43:09 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:09 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:43:09 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:09 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:43:09 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:43:10 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 63230, Aligned reads: 37364.

WARNING @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 121634, Substitutions outside window: 120762.

WARNING @ Fri, 12 Dec 2025 17:43:15 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 202775, Substitutions: 121634.

INFO  @ Fri, 12 Dec 2025 17:43:15 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:43:15 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:43:15 (11.8% done):
	 Completed 1/44 runs

INFO  @ Fri, 12 Dec 2025 17:43:16 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Fri, 12 Dec 2025 17:43:16 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG/CRISPResso_on_D1_A14_NGG-ABE_20_ul already exists.

INFO  @ Fri, 12 Dec 2025 17:43:16 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:43:16 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:43:16 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:43:17 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:17 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:17 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:43:18 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:43:18 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:43:18 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:43:18 (7.0% done):
	 Finished reading fastq file; 5235 unique reads found of 63057 total reads found

INFO  @ Fri, 12 Dec 2025 17:43:18 (7.0% done):
	 Processing Reads; 0 Completed out of 5235 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:43:19 (7.0% done):
	 Finished reads; N_TOT_READS: 63057 N_COMPUTED_ALN: 4333 N_CACHED_ALN: 40099 N_COMPUTED_NOTALN: 902 N_CACHED_NOTALN: 17723

INFO  @ Fri, 12 Dec 2025 17:43:19 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:19 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:43:20 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:20 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:43:20 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:20 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:43:20 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:43:20 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:43:27 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:27 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:27 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:43:27 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 63057, Aligned reads: 44432.

WARNING @ Fri, 12 Dec 2025 17:43:27 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 132931, Substitutions outside window: 132152.

INFO  @ Fri, 12 Dec 2025 17:43:27 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:43:27 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:43:27 (13.6% done):
	 Completed 2/44 runs

INFO  @ Fri, 12 Dec 2025 17:43:28 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Fri, 12 Dec 2025 17:43:28 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG/CRISPResso_on_D1_A14_NGG-ABE_2_ul already exists.

INFO  @ Fri, 12 Dec 2025 17:43:28 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:43:28 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:43:28 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:43:29 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:29 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:29 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:43:30 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:43:30 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:43:30 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:43:30 (7.0% done):
	 Finished reading fastq file; 4639 unique reads found of 69950 total reads found

INFO  @ Fri, 12 Dec 2025 17:43:30 (7.0% done):
	 Processing Reads; 0 Completed out of 4639 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:43:32 (7.0% done):
	 Finished reads; N_TOT_READS: 69950 N_COMPUTED_ALN: 3485 N_CACHED_ALN: 44244 N_COMPUTED_NOTALN: 1154 N_CACHED_NOTALN: 21067

INFO  @ Fri, 12 Dec 2025 17:43:32 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:32 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:43:32 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:32 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:43:32 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:32 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:43:32 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:43:32 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 69950, Aligned reads: 47729.

WARNING @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 233168, Substitutions outside window: 231672.

WARNING @ Fri, 12 Dec 2025 17:43:38 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 583202, Substitutions: 233168.

INFO  @ Fri, 12 Dec 2025 17:43:38 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:43:38 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:43:39 (15.5% done):
	 Completed 3/44 runs

INFO  @ Fri, 12 Dec 2025 17:43:39 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


WARNING @ Fri, 12 Dec 2025 17:43:39 (0.0% done):
	 Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_AtoG/CRISPResso_on_D1_B56_CBE_0-2_ul already exists.

INFO  @ Fri, 12 Dec 2025 17:43:39 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:43:39 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:43:39 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:43:40 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:40 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:40 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:43:42 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:43:42 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:43:42 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:43:42 (7.0% done):
	 Finished reading fastq file; 5095 unique reads found of 91807 total reads found

INFO  @ Fri, 12 Dec 2025 17:43:42 (7.0% done):
	 Processing Reads; 0 Completed out of 5095 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:43:44 (7.0% done):
	 Finished reads; N_TOT_READS: 91807 N_COMPUTED_ALN: 3121 N_CACHED_ALN: 39208 N_COMPUTED_NOTALN: 1974 N_CACHED_NOTALN: 47504

INFO  @ Fri, 12 Dec 2025 17:43:44 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:44 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:43:44 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:44 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:43:44 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:44 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:43:44 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:43:45 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 91807, Aligned reads: 42329.

WARNING @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 223233, Substitutions outside window: 221895.

WARNING @ Fri, 12 Dec 2025 17:43:50 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 602792, Substitutions: 223233.

INFO  @ Fri, 12 Dec 2025 17:43:50 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:43:50 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:43:51 (17.3% done):
	 Completed 4/44 runs

INFO  @ Fri, 12 Dec 2025 17:43:51 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \

In [42]:
##RunCRISPResso in CBE mode

!CRISPRessoBatch \
    --batch_settings refs/ABE-batch2.txt \
    --base_editor_output \
    --base_edit \
    --conversion_nuc_from C \
    --conversion_nuc_to T \
    --min_average_read_quality 25 \
    --min_single_bp_quality 20 \
    --default_min_aln_score 50 \
    --name BE_CtoT \
    --output_folder results/BE_CtoT

INFO  @ Fri, 12 Dec 2025 17:26:58 (0.0% done):

                             ~~~CRISPRessoBatch~~~
       -Analysis of CRISPR/Cas9 outcomes from batch deep sequencing data-

                _                                               _
               '  )                                            '  )
               .-'             _________________               .-'
              (____           | __    ___ __    |             (____
           C)|     \          ||__) /\ | /  |__||          C)|     \
             \     /          ||__)/--\| \__|  ||            \     /
              \___/           |_________________|             \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:26:59 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_CtoT

/opt/miniconda3/envs/crispresso2/lib/python3.12/site-packages/CRISPResso2/CRISPRessoBatchCORE.py:220: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  batch_params[arg] = getattr(args, arg)
INFO  @ Fri, 12 Dec 2025 17:26:59 (0.0% done):
	 Running CRISPResso with 1 processes

INFO  @ Fri, 12 Dec 2025 17:26:59 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:26:59 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_CtoT/CRISPResso_on_D1_A14_NGG-ABE_0-2_ul

INFO  @ Fri, 12 Dec 2025 17:26:59 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:26:59 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:26:59 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:27:00 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:00 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:00 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:27:01 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:27:01 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:27:01 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:27:01 (7.0% done):
	 Finished reading fastq file; 2710 unique reads found of 63230 total reads found

INFO  @ Fri, 12 Dec 2025 17:27:01 (7.0% done):
	 Processing Reads; 0 Completed out of 2710 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:27:02 (7.0% done):
	 Finished reads; N_TOT_READS: 63230 N_COMPUTED_ALN: 1618 N_CACHED_ALN: 35746 N_COMPUTED_NOTALN: 1092 N_CACHED_NOTALN: 24774

INFO  @ Fri, 12 Dec 2025 17:27:02 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:02 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:27:02 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:02 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:27:02 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:02 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:27:02 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:27:03 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 63230, Aligned reads: 37364.

WARNING @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 121634, Substitutions outside window: 120762.

WARNING @ Fri, 12 Dec 2025 17:27:08 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 202775, Substitutions: 121634.

INFO  @ Fri, 12 Dec 2025 17:27:08 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:27:08 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:27:08 (11.8% done):
	 Completed 1/44 runs

INFO  @ Fri, 12 Dec 2025 17:27:09 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:27:09 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_CtoT/CRISPResso_on_D1_A14_NGG-ABE_20_ul

INFO  @ Fri, 12 Dec 2025 17:27:09 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:27:09 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:27:09 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:27:10 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:10 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:10 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:27:11 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:27:11 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:27:11 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:27:11 (7.0% done):
	 Finished reading fastq file; 5235 unique reads found of 63057 total reads found

INFO  @ Fri, 12 Dec 2025 17:27:11 (7.0% done):
	 Processing Reads; 0 Completed out of 5235 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:27:12 (7.0% done):
	 Finished reads; N_TOT_READS: 63057 N_COMPUTED_ALN: 4333 N_CACHED_ALN: 40099 N_COMPUTED_NOTALN: 902 N_CACHED_NOTALN: 17723

INFO  @ Fri, 12 Dec 2025 17:27:12 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:12 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:27:13 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:13 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:27:13 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:13 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:27:13 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:27:13 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:27:19 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:19 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:19 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:27:19 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 63057, Aligned reads: 44432.

WARNING @ Fri, 12 Dec 2025 17:27:19 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 132931, Substitutions outside window: 132152.

INFO  @ Fri, 12 Dec 2025 17:27:19 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:27:19 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:27:19 (13.6% done):
	 Completed 2/44 runs

INFO  @ Fri, 12 Dec 2025 17:27:20 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:27:20 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_CtoT/CRISPResso_on_D1_A14_NGG-ABE_2_ul

INFO  @ Fri, 12 Dec 2025 17:27:20 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:27:20 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:27:20 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:27:21 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:21 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:21 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:27:22 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:27:22 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:27:23 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:27:23 (7.0% done):
	 Finished reading fastq file; 4639 unique reads found of 69950 total reads found

INFO  @ Fri, 12 Dec 2025 17:27:23 (7.0% done):
	 Processing Reads; 0 Completed out of 4639 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:27:24 (7.0% done):
	 Finished reads; N_TOT_READS: 69950 N_COMPUTED_ALN: 3485 N_CACHED_ALN: 44244 N_COMPUTED_NOTALN: 1154 N_CACHED_NOTALN: 21067

INFO  @ Fri, 12 Dec 2025 17:27:24 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:24 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:27:24 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:24 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:27:24 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:24 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:27:24 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:27:25 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 69950, Aligned reads: 47729.

WARNING @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 233168, Substitutions outside window: 231672.

WARNING @ Fri, 12 Dec 2025 17:27:31 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 583202, Substitutions: 233168.

INFO  @ Fri, 12 Dec 2025 17:27:31 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:27:31 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:27:31 (15.5% done):
	 Completed 3/44 runs

INFO  @ Fri, 12 Dec 2025 17:27:31 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]
[Note that as of version 2.3.0 FLASh and Trimmomatic have been replaced by fastp for read merging and trimming. Accordingly, the --flash_command and --trimmomatic_command parameters have been replaced with --fastp_command. Also, --trimmomatic_options_string has been replaced with --fastp_options_string.

Also in version 2.3.2, when running CRISPRessoPooled in mixed-mode (amplicon file and genome are provided) the default behavior will be as if the --demultiplex_only_at_amplicons parameter is provided. This change means that reads and amplicons do not need to align to the exact locations.]
       [For support contact k.clement@utah.edu or support@edilytics.com]


INFO  @ Fri, 12 Dec 2025 17:27:31 (0.0% done):
	 Creating Folder /Users/pdevant/crispresso_project/CRISPRessoBatch_on_BE_CtoT/CRISPResso_on_D1_B56_CBE_0-2_ul

INFO  @ Fri, 12 Dec 2025 17:27:31 (2.0% done):
	 Computing quantification windows

INFO  @ Fri, 12 Dec 2025 17:27:31 (2.0% done):
	 Counting reads in input

INFO  @ Fri, 12 Dec 2025 17:27:31 (2.0% done):
	 Processing sequences with fastp...

INFO  @ Fri, 12 Dec 2025 17:27:33 (6.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:33 (7.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:33 (7.0% done):
	 Filtering reads with average bp quality < 25 and single bp quality < 20 and replacing bases with quality < 0 with N ...

Completed in 1 seconds

INFO  @ Fri, 12 Dec 2025 17:27:34 (7.0% done):
	 Counting reads after preprocessing...

INFO  @ Fri, 12 Dec 2025 17:27:34 (7.0% done):
	 Aligning sequences...

INFO  @ Fri, 12 Dec 2025 17:27:34 (7.0% done):
	 Iterating over fastq file to identify reads; 50000 reads identified.

INFO  @ Fri, 12 Dec 2025 17:27:34 (7.0% done):
	 Finished reading fastq file; 5095 unique reads found of 91807 total reads found

INFO  @ Fri, 12 Dec 2025 17:27:34 (7.0% done):
	 Processing Reads; 0 Completed out of 5095 Unique Reads

INFO  @ Fri, 12 Dec 2025 17:27:36 (7.0% done):
	 Finished reads; N_TOT_READS: 91807 N_COMPUTED_ALN: 3121 N_CACHED_ALN: 39208 N_COMPUTED_NOTALN: 1974 N_CACHED_NOTALN: 47504

INFO  @ Fri, 12 Dec 2025 17:27:36 (20.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:36 (20.0% done):
	 Quantifying indels/substitutions...

INFO  @ Fri, 12 Dec 2025 17:27:36 (30.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:36 (30.0% done):
	 Calculating allele frequencies...

INFO  @ Fri, 12 Dec 2025 17:27:36 (40.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:36 (40.0% done):
	 Saving processed data...

INFO  @ Fri, 12 Dec 2025 17:27:36 (40.0% done):
	 Making Plots...

INFO  @ Fri, 12 Dec 2025 17:27:37 (48.0% done):
	 Begin processing plots for amplicon Reference

INFO  @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	 Done!

INFO  @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	 Removing Intermediate files...

WARNING @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	  <=90.0% of reads were aligned. Total reads: 91807, Aligned reads: 42329.

WARNING @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	  >=0.2% of substitutions were outside of the quantification window. Total substitutions: 223233, Substitutions outside window: 221895.

WARNING @ Fri, 12 Dec 2025 17:27:43 (48.0% done):
	  >=30.0% of modifications were substitutions. This could potentially indicate poor sequencing quality. Total modifications: 602792, Substitutions: 223233.

INFO  @ Fri, 12 Dec 2025 17:27:43 (48.0% done):

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/


INFO  @ Fri, 12 Dec 2025 17:27:43 (100.0% done):
	 Analysis Complete!

INFO  @ Fri, 12 Dec 2025 17:27:43 (17.3% done):
	 Completed 4/44 runs

INFO  @ Fri, 12 Dec 2025 17:27:43 (0.0% done):

                               ~~~CRISPResso 2~~~
        -Analysis of genome editing outcomes from deep sequencing data-

                                        _
                                       '  )
                                       .-'
                                      (____
                                   C)|     \
                                     \     /
                                      \___/

                           [CRISPResso version 2.3.3]